version: "3.9"
services:
  registry:
    image: 'my-rmi:0.0.1'
    container_name: 'myrmi-registry'
    network_mode: host
    environment:
      RUN_COMPONENT: 'REGISTRY'
  server:
    image: 'my-rmi:0.0.1'
    container_name: 'myrmi-server'
    network_mode: host
    depends_on:
      - registry
    environment:
      RUN_COMPONENT: 'SERVER'
  client:
    image: 'my-rmi:0.0.1'
    container_name: 'myrmi-client'
    network_mode: host
    depends_on:
      - registry
      - server
    environment:
      RUN_COMPONENT: 'CLIENT'

